package it.polito.netgroup.selforchestratingservices.compiler.model.json;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

public class VariableTypeDescription implements GenerateJavaClass
{
	public enum TYPE
	{
		entry
	}
	@JsonProperty("name")
	public String name;
	@JsonProperty("type")
	public TYPE type;
	@JsonProperty("params")
	public List<TypeParamDescription> params;
	
	
	@Override
	public String getJavaClassName(String prefix)
	{
		String className = prefix+name;

		return Character.toUpperCase(className.charAt(0)) + className.substring(1);
	}
	
	private String firstCharUpper(String string)
	{
		return Character.toUpperCase(string.charAt(0)) + string.substring(1);		
	}
	
	@Override
	public String getJavaClass(String prefix, SelfOrchestratorModel model, String pack)
	{
		String java = "package "+pack+";\n" + 
				"\n" +
				PackageGenerator.getPackage() +
				"\n" +
				"//Autogenerated code\n" + 
				"public class "+getJavaClassName(prefix)+"\n" + 
				"{\n"; 
				
		for( TypeParamDescription param : params )
		{
			java += "\t"+param.type + " " + param.name+";\n";
		}
		java += "\n"+
				"\tpublic "+getJavaClassName(prefix)+"(";
				
		for( TypeParamDescription param : params )
		{
			java += param.type + " _" + param.name+", ";
		}	
		java = java.substring(0, java.length()-2);
		
		java += ")\n" +
				"\t{\n";
		
		for( TypeParamDescription param : params )
		{
			java += "\t\t"+param.name + "= _" + param.name+";\n";
		}
		
		java += "\t}\n"+ 
				"\n";
				
		for( TypeParamDescription param : params )
		{
			java += "\tpublic "+param.type + " get" + firstCharUpper(param.name)+"(){\n";
			java += "\t\treturn "+param.name+";\n";
			java += "\t}\n";
		}				
				
		java += "}\n";

		
		return java;
	}
	
}
